package frontend.notifications;

import Backend.Account.Account;
import Backend.Databases.Databases;
import Backend.Databases.NotificationsDatabase;
import Backend.Notifications.*;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;

public class AddedToGroupNotiJPANEL extends javax.swing.JPanel {
    
    private Databases Database = Databases.getInstance();
    private NotificationsDatabase notiDatabase = NotificationsDatabase.getInstance();
    private JFrame mainwindow;
    private Account acc;
    private String groupName;
    private JPopupMenu popupmenu;
    
    public AddedToGroupNotiJPANEL(Account acc, Notification noti, JPopupMenu popupmenu, JFrame hometestwindow) {
        initComponents();
        Database.read();
        notiDatabase.read();
        this.mainwindow = hometestwindow;
        this.acc = acc;
        this.popupmenu = popupmenu;
        this.popupmenu.addPopupMenuListener(new PopupMenuListener() {
            @Override
            public void popupMenuWillBecomeVisible(PopupMenuEvent e) {
                if (Database.getAccount(acc.getUsername()).getNotiById(noti.getNotiID()).isOpenedBoolean()) {
                    unreadButton.setVisible(false);
                } else {
                    unreadButton.setVisible(true);
                    Database.getAccount(acc.getUsername()).getNotiById(noti.getNotiID()).setOpened(true);
                    notiDatabase.save();
                }
            }
            
            @Override
            public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
            }
            
            @Override
            public void popupMenuCanceled(PopupMenuEvent e) {
            }
        });
        this.groupName = ((AddedToGroupNoti) noti).getGroupName();
        messageLabel.setText(noti.getMessage());
        timeLabel.setText(noti.getTimestamp().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leaveButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        unreadButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        leaveButton.setBackground(new java.awt.Color(204, 0, 0));
        leaveButton.setText("LEAVE");
        leaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveButtonActionPerformed(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        timeLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        unreadButton.setBackground(new java.awt.Color(0, 204, 153));
        unreadButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        unreadButton.setText("UNREAD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(leaveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(unreadButton)
                        .addGap(112, 112, 112)
                        .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leaveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unreadButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void leaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveButtonActionPerformed
        Database.read();
        notiDatabase.read();
        Database.getGroup(groupName).removeMember(acc.getUsername());
        Database.getAccount(acc.getUsername()).removeALLGroupNotisbyGroupName(groupName);
        Database.save();
        notiDatabase.save();
        popupmenu.setVisible(false);
        JOptionPane.showMessageDialog(mainwindow, "Successfully left group: " + groupName + "!");
    }//GEN-LAST:event_leaveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton leaveButton;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JButton unreadButton;
    // End of variables declaration//GEN-END:variables
}
