/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.notifications;

import Backend.Account.Account;
import Backend.Databases.Databases;
import Backend.Databases.NotificationsDatabase;
import Backend.Notifications.FriendReqNoti;
import Backend.Notifications.Notification;
import frontend.general.hometest;
import java.awt.Dimension;
import java.time.format.DateTimeFormatter;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ButtonModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;

/**
 *
 * @author Mohamed
 */
public class friendReqNotiJPANEL extends javax.swing.JPanel {

    private Databases Database = Databases.getInstance();
    private NotificationsDatabase notiDatabase = NotificationsDatabase.getInstance();
    private JFrame mainwindow;
    private Account acc;
    private String sender;
    private JPopupMenu popupmenu;

    public friendReqNotiJPANEL(Account acc, Notification noti, JPopupMenu popupmenu, JFrame hometestwindow) {
        initComponents();
        Database.read();
        notiDatabase.read();
        this.mainwindow = hometestwindow;
        this.acc = acc;
        this.popupmenu = popupmenu;
        this.popupmenu.addPopupMenuListener(new PopupMenuListener() {
            @Override
            public void popupMenuWillBecomeVisible(PopupMenuEvent e) {
                if (Database.getAccount(acc.getUsername()).getNotiById(noti.getNotiID()).isOpenedBoolean()) {
                    unreadButton.setVisible(false);
                } else {
                    unreadButton.setVisible(true);
                    Database.getAccount(acc.getUsername()).getNotiById(noti.getNotiID()).setOpened(true);
                    notiDatabase.save();
                }
            }

            @Override
            public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
            }

            @Override
            public void popupMenuCanceled(PopupMenuEvent e) {
            }
        });
        this.sender = noti.getMessage().replace(" sent you a friend request!", "");
        messageLabel.setText(noti.getMessage());
        timeLabel.setText(noti.getTimestamp().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        declineButton = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        unreadButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        declineButton.setBackground(new java.awt.Color(204, 0, 0));
        declineButton.setText("DECLINE");
        declineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineButtonActionPerformed(evt);
            }
        });

        acceptButton.setBackground(new java.awt.Color(0, 204, 0));
        acceptButton.setText("ACCEPT");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        timeLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        unreadButton.setBackground(new java.awt.Color(0, 204, 153));
        unreadButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        unreadButton.setText("UNREAD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acceptButton)
                        .addGap(18, 18, 18)
                        .addComponent(declineButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(unreadButton)
                        .addGap(112, 112, 112)
                        .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(declineButton)
                        .addComponent(acceptButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unreadButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void notificationsConstructor() {
        jPopupMenu4.setLayout(new BoxLayout(jPopupMenu4, BoxLayout.Y_AXIS));
        jPopupMenu4.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        int counter = 0;
        for (Notification noti : Database.getAccount(acc.getUsername()).getNotifications()) {
            if (noti instanceof FriendReqNoti) {
                counter++;
                friendReqNotiJPANEL newjPanel = new friendReqNotiJPANEL(Database.getAccount(acc.getUsername()), noti, jPopupMenu4, this);
                jPopupMenu4.add(newjPanel);
            }
        }
        jPopupMenu4.setPreferredSize(new Dimension(411, (80 * counter)));

        notisToggle.getModel().addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                ButtonModel model = (ButtonModel) e.getSource();
                if (model.isPressed() && model.isArmed()) {
                    if (model.isSelected()) {
                        jPopupMenu4.show(notisToggle, 0, notisToggle.getHeight());
                    } else {
                        jPopupMenu4.setVisible(false);
                    }
                }
            }
        });
    }
    
    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        Database.read();
        notiDatabase.read();
        acc.getFriendsManagement().acceptFriendRequest(sender, acc.getUsername());
        Database.getAccount(acc.getUsername()).removeReqNotibySender(sender);
        Database.save();
        notiDatabase.save();
        popupmenu.setVisible(false);
        JOptionPane.showMessageDialog(mainwindow, "Friend request accepted!");
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void declineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineButtonActionPerformed
        Database.read();
        notiDatabase.read();
        acc.getFriendsManagement().declineFriendRequest(sender, acc.getUsername());
        Database.getAccount(acc.getUsername()).removeReqNotibySender(sender);
        Database.save();
        notiDatabase.save();
        popupmenu.setVisible(false);
        JOptionPane.showMessageDialog(mainwindow, "Friend request declined!");
    }//GEN-LAST:event_declineButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton declineButton;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JButton unreadButton;
    // End of variables declaration//GEN-END:variables
}
