/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

/**
 *
 * @author Zeina Hazem
 */
public class FriendsManagement extends javax.swing.JFrame {

    /**
     * Creates new form FriendsManagement
     */
    public FriendsManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        viewreqButton = new javax.swing.JButton();
        viewlistButton = new javax.swing.JButton();
        viewblockButton = new javax.swing.JButton();
        blockButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel1.setText("Friends Management");

        addButton.setBackground(new java.awt.Color(0, 204, 204));
        addButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addButton.setText("ADD FRIEND");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(0, 204, 204));
        removeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removeButton.setText("REMOVE FRIEND");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        viewreqButton.setBackground(new java.awt.Color(0, 204, 204));
        viewreqButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewreqButton.setText("VIEW FRIEND REQUESTS");
        viewreqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewreqButtonActionPerformed(evt);
            }
        });

        viewlistButton.setBackground(new java.awt.Color(0, 204, 204));
        viewlistButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewlistButton.setText("VIEW FRIENDS LIST");
        viewlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewlistButtonActionPerformed(evt);
            }
        });

        viewblockButton.setBackground(new java.awt.Color(0, 204, 204));
        viewblockButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewblockButton.setText("VIEW BLOCK LIST");
        viewblockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewblockButtonActionPerformed(evt);
            }
        });

        blockButton.setBackground(new java.awt.Color(0, 204, 204));
        blockButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        blockButton.setText("BLOCK");
        blockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(blockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewblockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewreqButton))))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(addButton)
                .addGap(34, 34, 34)
                .addComponent(removeButton)
                .addGap(36, 36, 36)
                .addComponent(viewreqButton)
                .addGap(30, 30, 30)
                .addComponent(viewlistButton)
                .addGap(33, 33, 33)
                .addComponent(viewblockButton)
                .addGap(32, 32, 32)
                .addComponent(blockButton)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeButtonActionPerformed

    private void viewreqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewreqButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewreqButtonActionPerformed

    private void viewlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewlistButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewlistButtonActionPerformed

    private void viewblockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewblockButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewblockButtonActionPerformed

    private void blockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton blockButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton viewblockButton;
    private javax.swing.JButton viewlistButton;
    private javax.swing.JButton viewreqButton;
    // End of variables declaration//GEN-END:variables
}
