/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.Settings;

/**
 *
 * @author Zeina Hazem
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        profilepic = new javax.swing.JLabel();
        coverpic = new javax.swing.JLabel();
        changepassButton = new javax.swing.JButton();
        changeprofileButton = new javax.swing.JButton();
        changecoverButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        changebioButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Settings");

        changepassButton.setBackground(new java.awt.Color(0, 204, 204));
        changepassButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        changepassButton.setText("CHANGE PASSWORD");
        changepassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepassButtonActionPerformed(evt);
            }
        });

        changeprofileButton.setBackground(new java.awt.Color(0, 204, 204));
        changeprofileButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        changeprofileButton.setText("CHANGE PROFILE PICTURE");

        changecoverButton.setBackground(new java.awt.Color(0, 204, 204));
        changecoverButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        changecoverButton.setText("CHANGE COVER PHOTO");

        jLabel3.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel3.setText("Settings");

        changebioButton.setBackground(new java.awt.Color(0, 204, 204));
        changebioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        changebioButton.setText("CHANGE BIO");

        logoutButton.setBackground(new java.awt.Color(0, 204, 204));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutButton.setText("LOGOUT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(294, 294, 294)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coverpic, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profilepic, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeprofileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changepassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changecoverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changebioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(profilepic))
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(coverpic))
                .addGap(18, 18, 18)
                .addComponent(changepassButton)
                .addGap(48, 48, 48)
                .addComponent(changeprofileButton)
                .addGap(50, 50, 50)
                .addComponent(changecoverButton)
                .addGap(43, 43, 43)
                .addComponent(changebioButton)
                .addGap(46, 46, 46)
                .addComponent(logoutButton)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changepassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepassButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changepassButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changebioButton;
    private javax.swing.JButton changecoverButton;
    private javax.swing.JButton changepassButton;
    private javax.swing.JButton changeprofileButton;
    private javax.swing.JLabel coverpic;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel profilepic;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
