package frontend.friends;

import Backend.Account.Account;
import Backend.Authentication.Register;
import Backend.Databases.Database;
import frontend.general.Home;

/**
 *
 * @author Zeina Hazem
 */
public class FriendsManagement extends javax.swing.JFrame {

    Account acc;

    public FriendsManagement() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.acc = acc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        viewreceivedreqButton = new javax.swing.JButton();
        viewlistButton = new javax.swing.JButton();
        viewblockButton = new javax.swing.JButton();
        viewsentreqButton = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        viewsuggestedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Friends Management");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel1.setText("Friends Management");

        addButton.setBackground(new java.awt.Color(0, 204, 204));
        addButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addButton.setText("ADD FRIEND");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        viewreceivedreqButton.setBackground(new java.awt.Color(0, 204, 204));
        viewreceivedreqButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewreceivedreqButton.setText("VIEW RECEIVED FRIEND REQUESTS");
        viewreceivedreqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewreceivedreqButtonActionPerformed(evt);
            }
        });

        viewlistButton.setBackground(new java.awt.Color(0, 204, 204));
        viewlistButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewlistButton.setText("VIEW FRIENDS LIST");
        viewlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewlistButtonActionPerformed(evt);
            }
        });

        viewblockButton.setBackground(new java.awt.Color(0, 204, 204));
        viewblockButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewblockButton.setText("VIEW BLOCK LIST");
        viewblockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewblockButtonActionPerformed(evt);
            }
        });

        viewsentreqButton.setBackground(new java.awt.Color(0, 204, 204));
        viewsentreqButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewsentreqButton.setText("VIEW PENDING FRIEND REQUESTS");
        viewsentreqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewsentreqButtonActionPerformed(evt);
            }
        });

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        viewsuggestedButton.setBackground(new java.awt.Color(0, 204, 204));
        viewsuggestedButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewsuggestedButton.setText("VIEW SUGGESTED FRIENDS");
        viewsuggestedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewsuggestedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(viewblockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewlistButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewreceivedreqButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewsentreqButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewsuggestedButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Home)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Home))
                .addGap(78, 78, 78)
                .addComponent(addButton)
                .addGap(18, 18, 18)
                .addComponent(viewsentreqButton)
                .addGap(18, 18, 18)
                .addComponent(viewreceivedreqButton)
                .addGap(18, 18, 18)
                .addComponent(viewlistButton)
                .addGap(18, 18, 18)
                .addComponent(viewblockButton)
                .addGap(18, 18, 18)
                .addComponent(viewsuggestedButton)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        FindUsers window = new FindUsers(acc);
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addButtonActionPerformed

    private void viewreceivedreqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewreceivedreqButtonActionPerformed
        // TODO add your handling code here:
        ViewReceivedFriendReq window = new ViewReceivedFriendReq(acc);
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewreceivedreqButtonActionPerformed

    private void viewlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewlistButtonActionPerformed
        // TODO add your handling code here:
        ViewFriendsList window = new ViewFriendsList(acc);
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewlistButtonActionPerformed

    private void viewblockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewblockButtonActionPerformed
        // TODO add your handling code here:
        ViewBlockList window = new ViewBlockList(acc);
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewblockButtonActionPerformed

    private void viewsentreqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewsentreqButtonActionPerformed
        // TODO add your handling code here:
        ViewSentFriendReq window = new ViewSentFriendReq(acc);
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewsentreqButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Register.getInstance().logout(acc);
    }//GEN-LAST:event_formWindowClosing

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Database.refreshDatabase();
        Home home = new Home(acc);
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void viewsuggestedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewsuggestedButtonActionPerformed
        // TODO add your handling code here:
        ViewSuggested window = new ViewSuggested(acc);
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewsuggestedButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewblockButton;
    private javax.swing.JButton viewlistButton;
    private javax.swing.JButton viewreceivedreqButton;
    private javax.swing.JButton viewsentreqButton;
    private javax.swing.JButton viewsuggestedButton;
    // End of variables declaration//GEN-END:variables
}
